void createBoard();
void createText(const char* text, SDL_Color color, int x, int y, TTF_Font* font);
void createMenu();
void initPNGs();
void cleanup();
void handlePlayingInput();
void handleMenuInput();
void handleMouseClick(SDL_MouseButtonEvent buttonEvent);
void movePiece(int fromX, int fromY, int toX, int toY);
bool isValidMove(int fromX, int fromY, int toX, int toY);
bool whiteRookValidMove(int fromX, int fromY, int toX, int toY);
bool blackRookValidMove(int fromX, int fromY, int toX, int toY);
bool whitePawnValidMove(int fromX, int fromY, int toX, int toY);
bool blackPawnValidMove(int fromX, int fromY, int toX, int toY);
bool whiteKnightValidMove(int fromX, int fromY, int toX, int toY);
bool blackKnightValidMove(int fromX, int fromY, int toX, int toY);
bool whiteBishopValidMove(int fromX, int fromY, int toX, int toY);
bool blackBishopValidMove(int fromX, int fromY, int toX, int toY);
bool whiteQueenValidMove(int fromX, int fromY, int toX, int toY);
bool blackQueenValidMove(int fromX, int fromY, int toX, int toY);
bool whiteKingValidMove(int fromX, int fromY, int toX, int toY);
bool blackKingValidMove(int fromX, int fromY, int toX, int toY);
bool whiteInCheck();
bool blackInCheck();
bool doesWhiteHaveMoves();
bool doesBlackHaveMoves();
bool whiteCheckMate();
bool blackCheckMate();
bool checkDraw();
Uint32 timerCallback(Uint32 interval, void* param);
void startTimer();
void renderTimer(Uint32 time, int x, int y);
void createEndScreen();
void handleEndInput();
void gameLoop();
bool gameIsOver();